# Generated by Django 5.1.2 on 2024-10-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
    ]
