# Generated by Django 5.1.2 on 2024-10-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_is_online'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
