# 使用官方的 PostgreSQL 映像作為基礎
FROM postgres:13

# 設定環境變數
ENV POSTGRES_USER hsh
ENV POSTGRES_PASSWORD "@Aa82851620"
ENV POSTGRES_DB mini_project

# 使用官方的 PostgreSQL Docker 設置工作目錄
VOLUME ["/var/lib/postgresql/data"]

# 暴露端口
EXPOSE 5432
